services:
  - type: web
    name: taskmanager
    runtime: docker
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: TaskManager
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: https://taskmanager-uvp6.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.npfuctogigxiivvqtuhs.supabase.co
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: Alimatou15.
      - key: DB_SSLMODE
        value: require
      - key: DB_SCHEMA
        value: taskmanager
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
